"use client";

import { useAuth } from "@/hooks/use-auth";
import { Card, CardContent, CardDescription, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { FileCode, Plus } from "lucide-react";
import DashboardLayout from "@/components/layouts/dashboard-layout";

export default function DashboardPage() {
  const { user, isLoading } = useAuth();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <DashboardLayout>
      <div className="container mx-auto py-6">
        <h1 className="text-2xl font-bold mb-6">Welcome, {user?.name}</h1>
        
        <Tabs defaultValue="blueprints" className="w-full">
          <TabsList className="grid w-full grid-cols-3 mb-4">
            <TabsTrigger value="blueprints">Blueprints</TabsTrigger>
            <TabsTrigger value="courses">Courses</TabsTrigger>
            <TabsTrigger value="events">Events</TabsTrigger>
          </TabsList>
          
          {/* Blueprints Tab */}
          <TabsContent value="blueprints" className="mt-0">
            <Card className="border-0 shadow-none">
              <CardContent className="flex flex-col items-center justify-center py-10 px-4 text-center">
                <FileCode className="h-12 w-12 text-muted-foreground mb-4" />
                <CardTitle className="mb-2">No Blueprints Yet</CardTitle>
                <CardDescription className="mb-6 max-w-md">
                  Blueprints are step-by-step guides generated by AI to help you accomplish specific tasks. 
                  Create your first blueprint to get started.
                </CardDescription>
                <Button>
                  <Plus className="mr-2 h-4 w-4" /> Create Blueprint
                </Button>
              </CardContent>
            </Card>
          </TabsContent>
          
          {/* Additional tabs would go here */}
        </Tabs>
      </div>
    </DashboardLayout>
  );
} 