import { NextResponse } from 'next/server';
import { createRouteHandler } from '@/utils/route-handlers';
import { OpenAI } from 'openai';

// Define response types to fix TypeScript errors
type SuccessResponse = { answer: string };
type ErrorResponse = { error: string; message?: string; suggestion?: string };
type ApiResponse = SuccessResponse | ErrorResponse;

/**
 * POST /api/blueprints/generate-answer
 * Generates a boilerplate answer for a blueprint question
 */
export const POST = createRouteHandler<ApiResponse>(
  ['POST'],
  async (req, { supabase, user }) => {
    try {
      // Parse request body
      const body = await req.json();
      const { question, blueprint_id, length = 'medium' } = body;
      
      if (!question || typeof question !== 'string') {
        return NextResponse.json(
          { error: 'Invalid input. Question content is required.' },
          { status: 400 }
        );
      }
      
      // Initialize OpenAI client
      const openai = new OpenAI({
        apiKey: process.env.OPENAI_API_KEY,
      });
      
      // Configure response length based on user preference
      let tokenLimit, paragraphCount, detailLevel;
      switch (length) {
        case 'short':
          tokenLimit = 150;
          paragraphCount = '1-2 short';
          detailLevel = 'very brief';
          break;
        case 'long':
          tokenLimit = 450;
          paragraphCount = '3-4';
          detailLevel = 'more detailed';
          break;
        case 'medium':
        default:
          tokenLimit = 300;
          paragraphCount = '2-3';
          detailLevel = 'concise';
          break;
      }
      
      // Log request for debugging
      console.log('Generating answer for question:', {
        question_preview: question.substring(0, 100) + (question.length > 100 ? '...' : ''),
        blueprint_id,
        length,
        has_user: !!user,
      });
      
      // Get blueprint context if available
      let blueprintPrompt = '';
      if (blueprint_id) {
        try {
          const { data: blueprintData, error } = await supabase
            .from('blueprints')
            .select('title, prompt')
            .eq('id', blueprint_id)
            .single();
            
          if (!error && blueprintData) {
            blueprintPrompt = `
            This is related to creating an AI blueprint for: "${blueprintData.title}"
            Blueprint description: "${blueprintData.prompt}"
            `;
          }
        } catch (err) {
          console.warn('Error fetching blueprint context (continuing anyway):', err);
        }
      }
      
      // Generate the answer using OpenAI
      const response = await openai.chat.completions.create({
        model: "gpt-3.5-turbo",
        messages: [
          { 
            role: "system", 
            content: `You are a helpful assistant that generates ${detailLevel} responses to questions about building AI systems. 
            Your goal is to be informative without overwhelming the user with too much detail.
            Keep responses practical, easy to understand, and focused on the most relevant information.
            ${blueprintPrompt}` 
          },
          { 
            role: "user", 
            content: `Please provide a ${detailLevel}, helpful response to this question about building an AI system:
            
            ${question}
            
            Keep your answer to about ${paragraphCount} paragraphs. Focus on the most important points, using simple language and avoiding excessive technical details.`
          }
        ],
        temperature: 0.7,
        max_tokens: tokenLimit,
      });
      
      // Extract the answer from the completion
      const answer = response.choices[0]?.message?.content?.trim();
      
      if (!answer) {
        throw new Error('No answer generated by the AI');
      }
      
      // Return the generated answer
      return NextResponse.json({ answer });
    } catch (error) {
      console.error('Error generating answer:', error);
      
      // Determine if it's an OpenAI error
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      const isRateLimitError = errorMessage.includes('rate limit') || errorMessage.includes('429');
      
      return NextResponse.json(
        { 
          error: 'Failed to generate answer',
          message: errorMessage,
          suggestion: isRateLimitError ? 'OpenAI rate limit reached. Please try again later.' : undefined
        },
        { status: 500 }
      );
    }
  }
); 